<h2><?php echo $this->translate("LocalResources.ContentPage.slide_about_titel");?></h2>

<p class="MyText"><?php echo $this->translate("LocalResources.ContentPage.slide_about_text_vision");?></p>
<p class="MyText"><?php echo $this->translate("LocalResources.ContentPage.slide_about_text_1");?></p>

<ul>
<li><?php echo $this->translate("LocalResources.ContentPage.slide_about_text_2");?></li>
<li><?php echo $this->translate("LocalResources.ContentPage.slide_about_text_3");?></li>
<li><?php echo $this->translate("LocalResources.ContentPage.slide_about_text_4");?></li>
</ul>
<br />

