<h2><?php echo $this->translate("LocalResources.ContentPage.slide_booking_titel");?></h2>

<p>
    <b>Albergo-Ristorante Bellavista</b><br />
	Via Costa Di Mezzo 77<br/>
	CH-6614 Brissago
</p>
<p>
    <?php echo $this->translate("LocalResources.ContentPage.slide_about_contact_phone"); ?> +41 91 793 12 22<br/>
	<?php echo $this->translate("LocalResources.ContentPage.slide_about_contact_fax"); ?> +41 91 793 29 19<br/>
	<a href="mailto:reservation@bellavista-brissago.ch?subject=Reservationsanfrage (Web)">E-Mail</a>: reservation@bellavista-brissago.ch<br/>
</p>

<p>
<?php echo $this->translate("LocalResources.ContentPage.slide_about_contact"); ?>
<a href="mailto:reservation@bellavista-brissago.ch?subject=Reservationsanfrage (Web)"><?php echo $this->translate("LocalResources.ContentPage.slide_about_contact_email"); ?></a>.
</p>

<br />
<br />
