<?php
echo $this->translate("LocalResources.ContentPage.slide_start_imagecaption_1");
echo $this->translate("LocalResources.ContentPage.slide_start_imagecaption_2");
echo $this->translate("LocalResources.ContentPage.slide_start_imagecaption_3");
echo $this->translate("LocalResources.ContentPage.slide_start_imagecaption_4");
echo $this->translate("LocalResources.ContentPage.slide_start_imagecaption_5");

echo $this->translate("LocalResources.ContentPage.slide_hotel_imagecaption_1");
echo $this->translate("LocalResources.ContentPage.slide_hotel_imagecaption_2");
echo $this->translate("LocalResources.ContentPage.slide_hotel_imagecaption_3");
echo $this->translate("LocalResources.ContentPage.slide_hotel_imagecaption_4");
echo $this->translate("LocalResources.ContentPage.slide_hotel_imagecaption_5");

echo $this->translate("LocalResources.ContentPage.slide_rooms_imagecaption_1");
echo $this->translate("LocalResources.ContentPage.slide_rooms_imagecaption_2");
echo $this->translate("LocalResources.ContentPage.slide_rooms_imagecaption_3");
echo $this->translate("LocalResources.ContentPage.slide_rooms_imagecaption_4");

echo $this->translate("LocalResources.ContentPage.slide_restaurant_imagecaption_1");
echo $this->translate("LocalResources.ContentPage.slide_restaurant_imagecaption_2");
echo $this->translate("LocalResources.ContentPage.slide_restaurant_imagecaption_3");
echo $this->translate("LocalResources.ContentPage.slide_restaurant_imagecaption_4");

echo $this->translate("LocalResources.ContentPage.slide_about_imagecaption_1");
echo $this->translate("LocalResources.ContentPage.slide_about_imagecaption_2");
echo $this->translate("LocalResources.ContentPage.slide_about_imagecaption_3");

?>