<h2><?php echo $this->translate("LocalResources.ContentPage.slide_hotel_titel"); ?></h2>

<p class="MyText"><b><?php echo $this->translate("LocalResources.ContentPage.slide_start_text_20years");?></b></p>

<p class="MyText"><?php echo $this->translate("LocalResources.ContentPage.slide_hotel_text_1"); ?></p>

<p class="MyText"><?php echo $this->translate("LocalResources.ContentPage.slide_start_text_2");?>
	<a target="_blank" href="/pdf/allg/Oeffnungszeiten.pdf">
		<img alt="" src="/public/images/icons/Download.jpg" height="18px" />
	</a>
</p>



