<h2><?php echo $this->translate("LocalResources.ContentPage.slide_start_titel");?></h2>

<h3><b>Das Hotel und Restaurant öffnet seine Tore wieder am 20. März.</b></h3>
</br>
<p class="MyText"><?php echo $this->translate("LocalResources.ContentPage.slide_start_text_1");?></p>

<p class="MyText">Lesen Sie, was der Buchautor, Publizist und Journalist Winfried Neun zur <a href="/pdf/allg/GourmetTicker15.pdf" target="_blank"_>Küche des Bellavista</a> schreibt.</p>
