<h2><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_titel"); ?></h2>

<p class="MyText"><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_text_1"); ?></p>

<div class="container">
    <div class="four columns">
        <h4><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_speisen"); ?></h4>
        <ul>
            <li>
                <a class="popup" id="lnkMenu44" target="_blank" href="<?php echo '/pdf/'.$this->layout()->culture.'/speisen/Season.pdf'; ?>">
                    <img alt="" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_speisen_spezial"); ?>
                </a>
            </li>
            <li>
                <a class="popup" id="lnkMenu11" target="_blank" href="<?php echo '/pdf/'.$this->layout()->culture.'/speisen/WarmeGerichte.pdf'; ?>">
                    <img alt="" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_speisen_warm"); ?>
                </a>
            </li>
            <li>
                <a class="popup" id="lnkMenu33" target="_blank" href="<?php echo '/pdf/'.$this->layout()->culture.'/speisen/SalateKaltespeisen.pdf'; ?>">
                    <img alt="" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_speisen_salat"); ?>
                </a>
            </li>
            <li>
                <a class="popup" id="lnkMenu66" target="_blank" href="<?php echo '/pdf/'.$this->layout()->culture.'/speisen/Kaese.pdf'; ?>">
                    <img alt="" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_speisen_kaese"); ?>
                </a>
            </li>
            <li>
                <a class="popup" id="lnkMenu55" target="_blank" href="<?php echo '/pdf/'.$this->layout()->culture.'/speisen/dessert.pdf'; ?>">
                    <img alt="" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_speisen_dessert"); ?>
                </a>
            </li>
        </ul>
    </div>

    <div class="four columns">
        <h4><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_weine_titel"); ?></h4>
        <ul>
            <li>
                <a class="popup" id="lnkMenu1" target="_blank" href="/pdf/weine/ch-rote.pdf">
                    <img alt="Rotweine" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_weine_ch_rot"); ?>
                </a>
            </li>
            <li>
                <a class="popup" id="lnkMenu2" target="_blank" href="/pdf/weine/it-rote.pdf">
                    <img alt="Rotweine" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_weine_it_rot"); ?>
                </a>
            </li>
            <li>
                <a class="popup" id="lnkMenu2" target="_blank" href="/pdf/weine/halbe-rote.pdf">
                    <img alt="Rotweine" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_weine_halbe_rot"); ?>
                </a>
            </li>
            <li>
                <a class="popup" id="lnkMenu3" target="_blank" href="/pdf/weine/weisse.pdf">
                    <img alt="Rotweine" src="/images/icons/pointer.jpg" height="18px" /><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_karte_weine_weisse"); ?>
                </a>
            </li>
        </ul>
    </div>

</div>
<br/>
<br/>
<p class="MyText"><?php echo $this->translate("LocalResources.ContentPage.slide_restaurant_text_opening"); ?></p>

<br />
