<h2><?php echo $this->translate("LocalResources.ContentPage.slide_specials_titel");?></h2>

<!-- 
<h4><?php echo $this->translate("LocalResources.ContentPage.slide_specials_subtitel1");?></h4>
<br/>
<p>
<?php echo $this->translate("LocalResources.ContentPage.slide_specials_text1_line1");?>
<br/>
<?php echo $this->translate("LocalResources.ContentPage.slide_specials_text1_line2");?>
<br />
<?php echo $this->translate("LocalResources.ContentPage.slide_specials_text1_line3");?>
</p>

<br/>
 -->
 
<h4><?php echo $this->translate("LocalResources.ContentPage.slide_specials_subtitel2");?></h4>
<br/>
<p>
<?php echo $this->translate("LocalResources.ContentPage.slide_specials_text2_line1");?>
<br/>
<?php echo $this->translate("LocalResources.ContentPage.slide_specials_text2_line2");?>
<br />
<?php echo $this->translate("LocalResources.ContentPage.slide_specials_text2_line3");?>
</p>

<br />
<br />
